name: Build and Release PerceptoMap (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  BUILD_DIR: build
  CMAKE_GENERATOR: "Visual Studio 17 2022"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: >
          cmake -B ${{ env.BUILD_DIR }}
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DVST3_GENERATE_MANIFEST=ON
          -DCMAKE_GENERATOR="${{ env.CMAKE_GENERATOR }}"

      - name: Build project
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Archive plugin (ZIP)
        run: |
             $pluginPath = "${{ env.BUILD_DIR }}\PerceptoMap_artefacts\${{ env.BUILD_TYPE }}\VST3\PerceptoMap.vst3"
             if (!(Test-Path $pluginPath)) {
               Write-Error "Plugin not found at expected path: $pluginPath"
               exit 1
             }
             Compress-Archive -Path $pluginPath -DestinationPath "PerceptoMap-vst3-win.zip"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: PerceptoMap-vst3-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}